# discord integration
discord:
  # enabled?
  enabled: false
  # bot token
  token: ""
  # chat channel id
  chat: ""
  # console channel id
  console: ""
  # status channel id
  status: ""
# regex kick chats
kickChats:
  - "dsc\\(?.\\(?gg/(?:2ch|matrix_v2)"
# regex blocked usernames
blockUsernames:
  - "\\d{10}"