# discord integration
discord:
  # enabled?
  enabled: false
  # bot token
  token: ""
  # chat channel id
  chat: ""
  # console channel id
  console: ""
  # status channel id
  status: ""
  # safe users, for admin commands
  safe:
    - "214118574485143553"
# captcha mode
captcha:
  enabled: false
  port: 8765
  secret: ""
  hostname: ""
  sitekey: ""
# whitelist
whitelist:
  enabled: false
  users:
    - "ayunami2000"
# regex kick chats
kickChats:
  - "dsc\\(?.\\(?gg\\/(?:2ch|matrix_v2)"
  - "https:\\/\\/discord\\.gg\\/4aN68dput4"
  - "vk com\\/amonitcraft"
# regex block chats
blockChats:
  - "@e"
  - "@a.*@a.*@a"
  - "^\\/?(?:essentials:)?e?sudo \\*"
# regex blocked usernames
blockUsernames:
  - "\\d{10}"
  - "2chan_\\d{6}"