name: ayunExtras
version: '${project.version}'
main: me.ayunami2000.ayunextras.AyunExtras
api-version: 1.17
load: STARTUP
authors: [ ayunami2000 ]
description: extras for my kaboom clone
commands:
  boost:
    description: ayunami2000's fun boost command!
    usage: /<command>
  ayunkick:
    description: only dumbasses forget to register their commands!
    usage: /<command>
  ayunrl:
    description: reload config for funi
    usage: /<command>
  ayuncap:
    description: toggle captcha mode
    usage: /<command>
  ayunwl:
    description: toggle whitelist
    usage: /<command>